## Topic Modelling

###### Latent Dirichlrt Allocation (LDA)
- This technique is on eof the many topic modeling technique
* spesific for text data!
* for some diffrent techniques you should research

for this method needs 2 thing 
    * bir matrikse dönüşmüş  dokuman (document-term matrix)
    * kaç tane konu istediğin ()

In [1]:
import pandas as pd
import pickle

In [2]:
data=pd.read_pickle("dtm_stop.pkl")
data

,aaaaah,aaah,aah,abc,abcs,ability,abject,able,ablebodied,abortion,...,yyou,ze,zealand,zeppelin,zero,zillion,zombie,zombies,zoning,zoo
ali,0,0,0,1,0,0,0,2,0,0,...,1,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,2,...,0,0,10,0,0,0,0,0,0,0
bill,1,0,0,0,1,0,0,1,0,0,...,0,1,0,0,1,1,1,1,1,0
dave,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,3,0,0,0,0,1,0,0,...,0,0,0,0,2,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,1,0,0,0,0,0
ricky,0,0,0,0,0,1,1,2,0,0,...,0,0,0,0,0,0,0,0,0,1

In [3]:
#conda install -c conda-forge gensim

In [4]:
#!pip install gensim

In [5]:
#pip install --upgrade gensim

In [6]:
# LDA metodu için gerekli kütüphaneler
from gensim import matutils , models
import scipy.sparse

In [7]:
# sutunu satır ,satırı sutun yapmak
tdm=data.transpose()
tdm.head()

        ali  anthony  bill  dave  jim  joe  louis  mike  ricky
aaaaah    0        0     1     0    0    0      0     0      0
aaah      0        0     0     1    0    0      0     0      0
aah       0        0     0     0    0    0      3     0      0
abc       1        0     0     0    0    0      0     0      0
abcs      0        0     1     0    0    0      0     0      0

In [8]:
# biz elimizdeki  matrix documenti  , yeni bir gensim formatına dönütürüyoruz
#Dataframe---->---- sparse matrix------> gensim 
sparse_counts=scipy.sparse.csr_matrix(tdm)
corpus= matutils.Sparse2Corpus(sparse_counts)

In [9]:
#gensim ayrıca "documentin" bütün terimlerinin olduğu kütüphaneye  ihtiyaç duyuyor
cv=pickle.load(open("cv_stop.pkl","rb"))
id2word=dict((v,k) for k, v in cv.vocabulary_.items())

######  şimdi elimizde corpus (matrixlenmiş dokuman)ve id2work(kelimelerin lokasyonu olan kütüphane)

###### geriye kaldı 2 şey 
###### konunun sayısı ve 
######  dokumanda ne kadar geçtiği

In [10]:
lda=models.LdaModel(corpus=corpus,id2word=id2word,num_topics=2,passes=10)

lda.print_topics()

[(0,
  '0.009*"shit" + 0.007*"said" + 0.007*"time" + 0.005*"fuck" + 0.005*"didn" + 0.005*"lot" + 0.005*"good" + 0.004*"life" + 0.004*"cause" + 0.004*"man"'),
 (1,
  '0.009*"said" + 0.008*"think" + 0.008*"fucking" + 0.007*"yeah" + 0.007*"ve" + 0.006*"say" + 0.006*"ll" + 0.006*"shit" + 0.005*"going" + 0.005*"went"')]

In [11]:
lda=models.LdaModel(corpus=corpus,id2word=id2word,num_topics=3,passes=10)

lda.print_topics()

[(0,
  '0.009*"think" + 0.008*"said" + 0.008*"fucking" + 0.007*"shit" + 0.006*"cause" + 0.006*"yeah" + 0.006*"ll" + 0.006*"thing" + 0.006*"guy" + 0.005*"going"'),
 (1,
  '0.007*"shit" + 0.005*"ok" + 0.005*"lot" + 0.005*"gotta" + 0.005*"oh" + 0.005*"wanna" + 0.004*"husband" + 0.004*"time" + 0.004*"women" + 0.004*"cause"'),
 (2,
  '0.012*"said" + 0.008*"ve" + 0.007*"didn" + 0.007*"fucking" + 0.007*"yeah" + 0.007*"say" + 0.005*"time" + 0.005*"joke" + 0.005*"shit" + 0.005*"went"')]

In [12]:
lda=models.LdaModel(corpus=corpus,id2word=id2word,num_topics=4,passes=10)

lda.print_topics()

[(0,
  '0.009*"said" + 0.008*"think" + 0.007*"cause" + 0.006*"fucking" + 0.006*"ll" + 0.006*"really" + 0.006*"thing" + 0.006*"ve" + 0.005*"day" + 0.005*"went"'),
 (1,
  '0.013*"said" + 0.009*"shit" + 0.008*"didn" + 0.008*"ahah" + 0.007*"time" + 0.007*"fuck" + 0.006*"fucking" + 0.006*"black" + 0.006*"man" + 0.005*"good"'),
 (2,
  '0.009*"shit" + 0.008*"yeah" + 0.008*"think" + 0.006*"fucking" + 0.006*"say" + 0.006*"fcking" + 0.006*"fck" + 0.005*"dude" + 0.005*"thing" + 0.005*"time"'),
 (3,
  '0.009*"ve" + 0.009*"said" + 0.009*"yeah" + 0.008*"fucking" + 0.008*"say" + 0.007*"went" + 0.006*"didn" + 0.006*"little" + 0.006*"ll" + 0.005*"joke"')]

These aren't looking so good . we have to modify our parametres.

lets modify!

## Topic modelling
### 2) Nouns only !

In [13]:
# hadi noun alrı kelimeleri ayıran bi fonksiyon yazalım

In [14]:
from nltk import word_tokenize , pos_tag
def nouns(text):
    is_noun=lambda pos :pos[:2]== "NN"
    tokenized = word_tokenize(text)
    all_nouns = [word for (word,pos) in pos_tag(tokenized) if is_noun(pos)]
    return " ".join(all_nouns)

In [15]:
data_clean=pd.read_pickle("data_clean.pkl")
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
dave     this is dave he tells dirty jokes for a living...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
louis    introfade the music out let’s roll hold there ...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [16]:
import nltk
#nltk.download("averaged_perceptron_tagger")
#nltk.download("punkt")

In [17]:
data_nouns=pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i ’ em i francisco city wor...
bill     thank s thank pleasure georgia area oasis t i ...
dave     jokes living stare work profound train thought...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fck thanks phone fckface ...
louis    music let ’ roll hold lights lights thank i t ...
mike     wow hey thanks look insane years everyone i t ...
ricky    hello thank fuck thank welcome i m gon tonight...

In [18]:
# sadece isimlerden oluşan bir dataframe oluşturuyoruz
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer


add_stop_words=["like" ,"im","know","jus","dont","thats","right","people",
               "youre","got","gonna","time","think","yeah","said"]

stop_words=text.ENGLISH_STOP_WORDS.union(add_stop_words) # eğer eklemek istediğiniz stop_wordsleri yukarıdaki dosyaya yazıp bu "line"ın sonuna(.union(add_stopwords))
#yukarda ingilizcedeki stop_wordsleri tanımladık
cvn=CountVectorizer(stop_words=stop_words)
data_cvn=cvn.fit_transform(data_nouns.transcript)
data_dtmn=pd.DataFrame(data_cvn.toarray(),columns=cvn.get_feature_names())
data_dtmn.index=data_nouns.index
data_dtmn
#Yukarda  sadece kelimelerden oluşan data_frame oluştuduk

C:\Users\ahmet\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaah,aah,abc,abcs,ability,abortion,abortions,abuse,accent,accents,...,youtube,yulin,yummy,ze,zealand,zeppelin,zillion,zombie,zombies,zoo
ali,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
anthony,0,0,0,0,0,2,0,0,1,0,...,0,0,0,0,10,0,0,0,0,0
bill,0,0,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,1,1,0
dave,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,1,1,1,...,2,0,0,0,0,0,0,0,0,0
louis,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
ricky,0,0,0,0,1,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,1

In [19]:
#gensim corpus oluşturuyoruz
corpusn=matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))
#kelime sözlüğü oluşturuyoruz
id2wordn= dict((v,k) for k,v in cvn.vocabulary_.items())

In [20]:
ldan=models.LdaModel(corpus=corpusn,id2word=id2wordn,num_topics=2,passes=10)

ldan.print_topics()

[(0,
  '0.014*"day" + 0.009*"thing" + 0.008*"women" + 0.008*"lot" + 0.008*"cause" + 0.007*"ve" + 0.006*"baby" + 0.006*"shit" + 0.006*"guy" + 0.006*"fuck"'),
 (1,
  '0.010*"gon" + 0.010*"thing" + 0.009*"shit" + 0.009*"cause" + 0.009*"life" + 0.008*"man" + 0.008*"guy" + 0.007*"way" + 0.006*"day" + 0.006*"things"')]

In [21]:
ldan=models.LdaModel(corpus=corpusn,id2word=id2wordn,num_topics=3,passes=10)

ldan.print_topics()

[(0,
  '0.014*"shit" + 0.011*"lot" + 0.010*"man" + 0.009*"ahah" + 0.008*"women" + 0.008*"fuck" + 0.006*"gon" + 0.005*"woman" + 0.005*"cause" + 0.005*"husband"'),
 (1,
  '0.012*"thing" + 0.011*"day" + 0.010*"cause" + 0.010*"gon" + 0.009*"life" + 0.009*"guy" + 0.007*"man" + 0.007*"way" + 0.007*"shit" + 0.007*"ve"'),
 (2,
  '0.001*"man" + 0.001*"ahah" + 0.001*"shit" + 0.001*"guy" + 0.001*"lot" + 0.001*"way" + 0.001*"fuck" + 0.001*"things" + 0.001*"gon" + 0.001*"ve"')]

In [22]:
ldan=models.LdaModel(corpus=corpusn,id2word=id2wordn,num_topics=4,passes=10)

ldan.print_topics()

[(0,
  '0.013*"fck" + 0.009*"gon" + 0.009*"day" + 0.009*"thing" + 0.008*"man" + 0.008*"house" + 0.008*"joke" + 0.008*"things" + 0.007*"world" + 0.007*"cause"'),
 (1,
  '0.013*"thing" + 0.013*"day" + 0.009*"guy" + 0.009*"gon" + 0.008*"ve" + 0.008*"fuck" + 0.008*"shit" + 0.007*"man" + 0.007*"cause" + 0.007*"don"'),
 (2,
  '0.014*"ahah" + 0.013*"shit" + 0.012*"man" + 0.010*"fuck" + 0.008*"lot" + 0.006*"guy" + 0.006*"money" + 0.006*"room" + 0.006*"woman" + 0.006*"women"'),
 (3,
  '0.014*"cause" + 0.010*"life" + 0.010*"gon" + 0.009*"thing" + 0.008*"lot" + 0.007*"day" + 0.007*"women" + 0.007*"shit" + 0.007*"guy" + 0.007*"kind"')]

### Topic modelling -3
###### Nouns and Adjectives

In [23]:
def nouns_adj(text):
    is_noun_adj=lambda pos :pos[:2]== "NN"or pos[:2]=="JJ"
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word,pos) in pos_tag(tokenized) if is_noun_adj(pos)]
    return " ".join(nouns_adj)

In [24]:
data_nouns_adj=pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i ’ em i francisco city wor...
bill     thank s thank pleasure georgia area oasis t i ...
dave     jokes living stare work profound train thought...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fck thanks phone fckface ...
louis    music let ’ roll hold lights lights thank i t ...
mike     wow hey thanks look insane years everyone i t ...
ricky    hello thank fuck thank welcome i m gon tonight...

In [25]:
add_stop_words=["like" ,"im","know","jus","dont","thats","right","people",
               "youre","got","gonna","time","think","yeah","said"]

stop_words=text.ENGLISH_STOP_WORDS.union(add_stop_words) # eğer eklemek istediğiniz stop_wordsleri yukarıdaki dosyaya yazıp bu "line"ın sonuna(.union(add_stopwords))
#yukarda ingilizcedeki stop_wordsleri tanımladık
cvna=CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna=cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna=pd.DataFrame(data_cvna.toarray(),columns=cvna.get_feature_names())
data_dtmna.index=data_nouns_adj.index
data_dtmna

C:\Users\ahmet\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaah,aah,abc,abcs,ability,abject,able,ablebodied,abortion,abortions,...,yulin,yummy,yyou,ze,zealand,zeppelin,zillion,zombie,zombies,zoo
ali,0,0,1,0,0,0,2,0,0,0,...,0,0,1,0,0,0,0,1,0,0
anthony,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,10,0,0,0,0,0
bill,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,1,1,1,0
dave,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
ricky,0,0,0,0,1,1,2,0,0,0,...,1,1,0,0,0,0,0,0,0,1

In [26]:
#gensim corpus oluşturuyoruz
corpusna=matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))
#kelime sözlüğü oluşturuyoruz
id2wordna= dict((v,k) for k,v in cvna.vocabulary_.items())

In [27]:
ldana=models.LdaModel(corpus=corpusna,id2word=id2wordna,num_topics=2,passes=10)

ldana.print_topics()

[(0,
  '0.009*"fck" + 0.006*"everybody" + 0.005*"ok" + 0.005*"kid" + 0.005*"different" + 0.004*"fcking" + 0.003*"tit" + 0.003*"husband" + 0.003*"mom" + 0.003*"course"'),
 (1,
  '0.008*"fuck" + 0.007*"fucking" + 0.006*"joke" + 0.004*"kid" + 0.003*"gun" + 0.003*"everybody" + 0.003*"ahah" + 0.003*"son" + 0.003*"family" + 0.003*"okay"')]

In [28]:
ldana=models.LdaModel(corpus=corpusna,id2word=id2wordna,num_topics=3,passes=10)

ldana.print_topics()

[(0,
  '0.000*"fck" + 0.000*"everybody" + 0.000*"fucking" + 0.000*"fuck" + 0.000*"kid" + 0.000*"okay" + 0.000*"fcking" + 0.000*"ahah" + 0.000*"door" + 0.000*"uh"'),
 (1,
  '0.009*"fuck" + 0.007*"everybody" + 0.006*"fucking" + 0.005*"kid" + 0.005*"ahah" + 0.005*"ok" + 0.003*"let" + 0.003*"gay" + 0.003*"course" + 0.003*"tit"'),
 (2,
  '0.007*"joke" + 0.006*"fck" + 0.004*"fucking" + 0.004*"kid" + 0.004*"fuck" + 0.004*"different" + 0.004*"sure" + 0.004*"jokes" + 0.004*"okay" + 0.004*"funny"')]

In [29]:
ldana=models.LdaModel(corpus=corpusna,id2word=id2wordna,num_topics=4,passes=10)

ldana.print_topics()

[(0,
  '0.014*"ahah" + 0.010*"fuck" + 0.007*"gay" + 0.005*"fucking" + 0.005*"oj" + 0.005*"son" + 0.005*"kevin" + 0.005*"ghetto" + 0.004*"everybody" + 0.004*"young"'),
 (1,
  '0.010*"fuck" + 0.009*"fucking" + 0.007*"everybody" + 0.007*"kid" + 0.006*"gun" + 0.004*"jesus" + 0.004*"sudden" + 0.004*"sense" + 0.004*"religion" + 0.004*"trouble"'),
 (2,
  '0.007*"joke" + 0.006*"course" + 0.005*"nuts" + 0.005*"tit" + 0.004*"fucking" + 0.004*"food" + 0.004*"ha" + 0.004*"jenner" + 0.004*"dog" + 0.004*"kid"'),
 (3,
  '0.007*"fck" + 0.005*"kid" + 0.005*"fuck" + 0.005*"uh" + 0.004*"sure" + 0.004*"joke" + 0.004*"jenny" + 0.004*"different" + 0.004*"everybody" + 0.004*"fucking"')]

# Her dokumanda konuyu belirlemek
### Identify Topics in Each Doucment

In [30]:
# our final LDA model
ldana=models.LdaModel(corpus=corpusna,id2word=id2wordna,num_topics=4,passes=10)

ldana.print_topics()

[(0,
  '0.007*"fuck" + 0.007*"joke" + 0.006*"kid" + 0.006*"guns" + 0.005*"fucking" + 0.005*"course" + 0.005*"dog" + 0.004*"gun" + 0.004*"anthony" + 0.004*"family"'),
 (1,
  '0.009*"fck" + 0.007*"everybody" + 0.006*"kid" + 0.005*"jenny" + 0.005*"fuck" + 0.004*"fcking" + 0.004*"fucking" + 0.004*"okay" + 0.004*"religion" + 0.003*"weird"'),
 (2,
  '0.010*"joke" + 0.006*"nuts" + 0.005*"fucking" + 0.005*"jenner" + 0.005*"hampstead" + 0.005*"chimp" + 0.005*"funny" + 0.005*"twitter" + 0.005*"rape" + 0.004*"jane"'),
 (3,
  '0.009*"ahah" + 0.009*"fuck" + 0.005*"husband" + 0.005*"gay" + 0.005*"ok" + 0.005*"fucking" + 0.004*"everybody" + 0.004*"asian" + 0.004*"pregnant" + 0.003*"son"')]

In [31]:
# şimdi her transcript hangi konuyu içeriyor ona bi bakalım
corpus_transformed=ldana[corpusna]
list(zip([a for [(a,b)]in corpus_transformed],data_dtmna.index))

[(3, 'ali'),
 (0, 'anthony'),
 (1, 'bill'),
 (3, 'dave'),
 (0, 'jim'),
 (1, 'joe'),
 (0, 'louis'),
 (1, 'mike'),
 (2, 'ricky')]

In [32]:
# Bunların mantıklı bir anlamı var bunlara sonra değincez

- Topic 0 : mom,parents
- Topic 1 :husband,wife
- Topic 2 :guns
- Topic 3 :profanity